### ISSUE TITLE
Request: no lines for blanks in black&white mode

### ISSUE THREAD

**Issue by jotego** [gtkwave/gtkwave#106]
The black & white mode is very convenient because of its high contrast. But as soon as I plot a few signals, it gets confusing. Using blanks to space signals out doesn't help because blanks are represented as a constant low signal, so it just adds more clutter.

Would it be possible **to make blanks blank**? This also happens in colour mode but because of the dark blue used is not as bad.

![Captura de pantalla de 2021-12-21 16-06-07](https://user-images.githubusercontent.com/1863036/146952185-32263154-318d-4986-8c80-c8822e4188b4.png)

**Comment by rfuest** [comment]
I'm currently working on rewriting the waveform widget and could include this in my PR. With the my changes it would be easy to use the print colors for the black and white mode:
![grafik](https://user-images.githubusercontent.com/226123/146965689-9e5c4f0a-fb09-43a8-8d1a-b11437bbaf12.png)
Maybe the grid lines could be made a bit darker to improve visibility.

**Comment by jotego** [comment]
I see you're drawing the blank rows as light gray lines. That's nice too.

**Comment by gtkwave** [comment]
Use View->Show Grid toggled to off.
-Tony

    On Tuesday, December 21, 2021, 11:28:43 AM EST, Jose Tejada ***@***.***> wrote:  
 
 


The black & white mode is very convenient because of its high contrast. But as soon as I plot a few signals, it gets confusing. Using blanks to space signals out doesn't help because blanks are represented as a constant low signal, so it just adds more clutter.

Would it be possible to make blanks blank? This also happens in colour mode but because of the dark blue used is not as bad.



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jotego** [comment]
It was so simple it embarrases me :-)
Thank you

**Comment by rfuest** [comment]
@gtkwave What is you opinion on changing the black and white mode to use some grayscale colors? Or do you think that both, a real black and white and a grayscale mode should exist? The current output of the black and white mode has some issues and hides some information, e.g. `U`, `W`, `X` and `-` values are all rendered as a black box without a label.

**Comment by gtkwave** [comment]
Grayscale is fine.  Its sole intent was for much higher contrast than the usual color traces.
-Tony

    On Thursday, December 23, 2021, 02:04:28 PM EST, Ralf Fuest ***@***.***> wrote:  
 
 


@gtkwave What is you opinion on changing the black and white mode to use some grayscale colors? Or do you think that both, a real black and white and a grayscale mode should exist? The current output of the black and white mode has some issues and hides some information, e.g. U, W, X and - values are all rendered as a black box without a label.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
