### ISSUE TITLE
gtkwave source code generation 

### ISSUE THREAD

**Issue by NourFr10** [gtkwave/gtkwave#119]
Hi Tony,
Could you please tell me which platform did you used to design and generate the gtkwave source code ? is it glade ? or did you hardcoded all the stuff ? 

Thank you

**Comment by gtkwave** [comment]
It's all been written by hand either by me or various contributors over the years.

-Tony

    On Friday, April 1, 2022, 11:49:33 AM EDT, NourFr ***@***.***> wrote:  
 
 


Hi Tony,
Could you please tell me which plateforme did you used to design and generate the gtkwave source code ? is it glade ? or did you hardcoded all the stuff ?

Thank you
