### ISSUE TITLE
Signal right-click "Open Scope" not working with FST files

### ISSUE THREAD

**Issue by wltr** [gtkwave/gtkwave#159]
I am used to being able to open the scope of a signal in the tree hierarchy by right-clicking on the signal and then clicking "Open Scope". This used to work with VCD files but somehow doesn't seem to do anything with FST files. (gtkwave v3.3.111)

**Comment by gtkwave** [comment]
I wonder if it's broken in the github version (which I don't use)--I don't have time to check that version, but at least the git directory on my PC seems to work.
If it's not the viiewer, something weird is going on with your model.  I use that feature every day.  I just tried in on the des.fst in examples/  Is there some kind of weirdness with escaped hierarchies or something similar?
https://sourceforge.net/projects/gtkwave/files/
...try one of the appropriate versions found here as those are prior to any of the github-specific changes.

-Tony

    On Tuesday, October 11, 2022, 02:20:48 PM EDT, Johannes Walter ***@***.***> wrote:  
 
 


I am used to being able to open the scope of a signal in the tree hierarchy by right-clicking on the signal and then clicking "Open Scope". This used to work with VCD files but somehow doesn't seem to do anything with FST files. (gtkwave v3.3.111)

**Comment by wltr** [comment]
Thanks for the reply! It works on `des.fst` with my version too. Looks like that is generated by Icarus. My FST files are generated by Verilator (fstWriter). I'll check in their code.

**Comment by wltr** [comment]
I found that it was my use of Verilator + SystemC + FST. After instantiating the DUT within my test module, the top-level name became "test.dut". I assume that "." is used as the scope delimiter. So, in this case, the scope could not be resolved. Instantiating the DUT outside the test class and passing it in, changed the top-level name to just "dut" and everything works as expected.
