### ISSUE TITLE
FST Specification

### ISSUE THREAD

**Issue by Timmmm** [gtkwave/gtkwave#174]
Following on from our discussion in #122 I thought you might like to see my first draft of a specification for FST:

https://blog.timhutt.co.uk/fst_spec/

I haven't figured out some things out yet and I'm sure there are mistakes (proof reading very welcome!) but I think I am going to implement a reader library in Rust next. That will hopefully highlight any issues.

**Comment by gtkwave** [comment]
Quite an impressive tear down.  It looks largely correct but I'd have to sit down for quite a while on the finer points such as where double compression using LZ4 is used, etc.

Also, there is a magic number of sorts...but it's not at position zero.
see around line 664 in debug.c of gtkwave where the match on the double for "e" is checked.  

The intent largely was to throw well known transcendental numbers out there, somewhat as a joke, but also to determine endianness.  Use a different number, then it's a different version of FST.  Keep in mind when this was initially developed (2009), big-endian PowerPC was still a competitor--and I was working at IBM at that time related to processor design and was doing a lot of development on AIX machines.

Dynamic aliases were a bit of a hack in their encoding.  Some of the format evolved in an upwardly compatible fashion where various new features could be slid in without wrecking the ability to support old readers.  The last thing I wanted to do was to support multiple readers.  I'm surprised the format has lasted this long, largely unchanged.

-Tony



    On Wednesday, November 30, 2022, 05:13:57 PM EST, Tim ***@***.***> wrote:  
 
 


Following on from our discussion in #122 I thought you might like to see my first draft of a specification for FST:

https://blog.timhutt.co.uk/fst_spec/

I haven't figured out some things out yet and I'm sure there are mistakes (proof reading very welcome!) but I think I am going to implement a reader library in Rust next. That will hopefully highlight any issues.

**Comment by Timmmm** [comment]
> Quite an impressive tear down.

Thanks!

> Also, there is a magic number of sorts...

Ah interesting point! I will add a note about that, thanks.

**Comment by NourFr10** [comment]
Oh, I was searching for such wonderful spec long time ago, I thank you @Timmmm for the effort

**Comment by Timmmm** [comment]
By the way @gtkwave I don't suppose you have any really massive FST files I could use for stress testing? Like 10GB or similar.

**Comment by gtkwave** [comment]
I have big ones but they're work-related so I can't give them out.
Note that there are two different/simultaneous directions for stress testing:lots of signalslots of timesteps
Note that with what's in gtkwave, I've tested in the tens of millions of signals range.

-Tony

    On Saturday, December 3, 2022, 10:52:41 AM EST, Tim ***@***.***> wrote:  
 
 


By the way @gtkwave I don't suppose you have any really massive FST files I could use for stress testing? Like 10GB or similar.

**Comment by Timmmm** [comment]
Ah shame. I'm in the same boat, though we mostly use VCS anyway.

I guess I will try an open source RISC-V processor or something. Maybe won't get to millions of signals but it'll have to do!
