### ISSUE TITLE
Are VList spill files in VCD recoder still useful?

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#189]
I'm currently working on refactoring the VCD parsers for GtkWave 4 and hope to be able to share some initial results sometime next month.

Are using VList prepacking, spill files and fastload still useful features, that should be kept for GtkWave 4, or are they superseded by converting VCD files to FST before loading them in GtkWave (or by using the `--optimize` option)?

Are there any other old features that come to your mind that could be removed? I've already started to remove the `atomic_vectors` setting, which was mentioned in a recent GH issue.

**Comment by gtkwave** [comment]
Spill files are no longer useful given there is FST, so yes, I'd say they can be removed.  

-Tony

    On Monday, February 27, 2023 at 10:37:13 PM EST, Ralf Fuest ***@***.***> wrote:  
 
 


I'm currently working on refactoring the VCD parsers for GtkWave 4 and hope to be able to share some initial results sometime next month.

Are using VList prepacking, spill files and fastload still useful features, that should be kept for GtkWave 4, or are they superseded by converting VCD files to FST before loading them in GtkWave (or by using the --optimize option)?

Are there any other old features that come to your mind that could be removed? I've already started to remove the atomic_vectors setting, which was mentioned in a recent GH issue.
