### ISSUE TITLE
Removing GTK2 support from the non LTS version

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#221]
I would like to simplify some code in the non LTS version by removing GTK 2 support and requiring the latest GTK 3 version. GTK 3.24 is now 4 years old and should be available for most users. If I remember correctly the main issue with removing GTK 2 was that there were problems with macOS and GTK 3. But they could now use the LTS version instead.

**Comment by gtkwave** [comment]
That sounds fine to me.
-Tony

    On Monday, July 24, 2023 at 10:48:08 AM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


I would like to simplify some code in the non LTS version by removing GTK 2 support and requiring the latest GTK 3 version. GTK 3.24 is now 4 years old and should be available for most users. If I remember correctly the main issue with removing GTK 2 was that there were problems with macOS and GTK 3. But they could now use the LTS version instead.

**Comment by alexforencich** [comment]
Please don't do this until https://github.com/gtkwave/gtkwave/issues/173 is resolved.
