### ISSUE TITLE
Moving from autotools to meson

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#225]
I did recently run into some issues with the current autotools setup and I started to miss the painless experience I had with meson, which I'm using for GTKWave 4. If there is no opposition against it I would like to move to meson for GTKWave 3.4.

Some of the main advantages of using meson IMO:
- Much easier syntax and easier to modify for non autotools experts.
- Good support for GTK/GNOME based projects.
   The [GNOME module](https://mesonbuild.com/Gnome-module.html) in meson makes GTK specific build steps simpler to implement. Most (all?) GNOME applications have moved to meson and support for GNOME in meson seems to be better maintained and documented than the autotools equivalents.
- Faster.
  Maybe not a huge difference, but at least running `configure` on Windows was very slow and should be a lot faster with meson: https://mesonbuild.com/Simple-comparison.html
- Out of tree builds.
  Meson uses a separate build directory instead of putting `.o` files next to the source files. This reduces clutter in the source directory and also makes it possible to have multiple build directories at once, for example to compare different build configurations.

Possible disadvantages:
- Will require a one time change to all distro packages.
- I cannot port the macOS support over to meson, because I don't have access to macOS.

**Comment by gtkwave** [comment]
Autotools is getting long in the tooth.  It was great when it came out and beat the heck out of writing complex Makefiles by hand, but decades later there are better options.  Sure, I'm ok with Meson--especially if it's the direction where GTK/Gnome application development has gone.

-Tony
