### ISSUE TITLE
Inserting signals from Hierarchy Search is broken

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#228]
The "Hierarchy Search" window doesn't seem to behave like it is described in the user guide. Adding an entire module, if no signal is selected, works as expected. But the Append button doesn't do anything if a signal is selected.

Should we fix this issue or remove the dialog entirely? Does it provide any functionality that the SST doesn't have? The append command for single traces was apparently broken in this commit: https://github.com/rfuest/gtkwave-archive/commit/e08d7e3b75ecdbcab4f5d8436ebc39d8bda1a740 If a feature didn't work for 6 years and nobody has complained it might be safe to remove.

**Comment by gtkwave** [comment]
Hierarchy Search can be removed.  It predated the SST by years and I doubt anyone uses it anymore.

-Tony
