### ISSUE TITLE
Update the GTKWave icon

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#242]
The current GTKWave icon has some technical issues, because it is not scalable. There is a SVG version, but it doesn't scale and is just a bitmap file embedded in a SVG file.

On a more subjective level I also think that the logo is looking a bit outdated. The logo seems to be designed to be displayed in a 4:3 aspect ratio, but it was squished to be square at some point, which results in inconsistent line widths.

Here is my suggestion for a redesigned logo, which follows the application icon suggestions in the GNOME HIG:

![grafik](https://github.com/gtkwave/gtkwave/assets/226123/a1759036-7273-4e1a-81c0-7eeb7be04994)

The symbolic version isn't rendered correctly in the preview and should look like this:

![grafik](https://github.com/gtkwave/gtkwave/assets/226123/cf21d1f2-1e79-489c-8ae1-22b355aab9f3)

**Comment by gtkwave** [comment]
"It's an icon."  Pick whatever you think looks OK.  I think all modern "flat" icons look bad, but that's where the world has headed.  What you have looks better than the usual two color stuff I see on Windows.  Five years from now, the Steampunk look might be in vogue.  :-)

I can't remember how long the current gtkwave icon has been around, but it's been a very long time.  From the changelog, it looks like the SVG was a user submission to me for 3.3.71 in 2016.  Any existing ones from a previous install probably are buried under /usr/share/icons/ or something similar.  The name "gtkwave" found in a filename under share or local is usually a good way to find those files.

-Tony
