### ISSUE TITLE
xml2stems command is not found

### ISSUE THREAD

**Issue by needhnlxf** [gtkwave/gtkwave#247]
Command is not found when I use xml2stems on centos 7.
(gtkwave version is 3.3.61)
(I install it through "yum install gtkwave")
Can you help me?

**Comment by gtkwave** [comment]
The xml2stems command was added in 3.3.93.  As it is a C++ executable, you'll have to build it from source from a recent tar file.

-Tony

    On Thursday, September 7, 2023 at 04:37:33 AM EDT, needhnlxf ***@***.***> wrote:  
 
 


Command is not found when I use xml2stems on centos 7.
(gtkwave version is 3.3.61)
(I install it through "yum install gtkwave")
Can you help me?

**Comment by needhnlxf** [comment]
Ok, it is working. Thanks!
