### ISSUE TITLE
Remove legacy VCD loader?

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#257]
Is there a reason to keep the legacy VCD loader? I guess it was kept as a fallback, but I think the VCD recoder has proven to be reliable in the last 17 years.

**Comment by gtkwave** [comment]
"Is there a reason to keep the legacy VCD loader? I guess it was kept as a fallback, but I think the VCD recoder has proven to be reliable in the last 17 years."

  Message ID: ***@***.***>Yes, I'd say it can be removed.  I can't recall the last time I deliberately wanted or needed to load a trace with it.

-Tony
