### ISSUE TITLE
Show the frequency of a signal between the markers

### ISSUE THREAD

**Issue by LiamSkirrow** [gtkwave/gtkwave#267]
As well as showing the quantity, `cursor-baseline`, it'd be very cool to have an additional (optional) quantity showing the frequency (really just `1/(cursor-baseline)`) in the relevant units, probably defaulting to MHz. This would make verifying the frequency of clock signals much simpler.

Sounds like a relatively simple addition, may I produce a PR for this change?

**Comment by rfuest** [comment]
Try `View->Toggle Delta-Frequency` in the menu.

**Comment by LiamSkirrow** [comment]
Ah it's already a feature, thanks for the help 👍
