### ISSUE TITLE
GTK wave is not working macbook software: sonoma 14.1

### ISSUE THREAD

**Issue by Khizarkk7** [gtkwave/gtkwave#281]
<img width="963" alt="Screenshot 2023-11-03 at 7 45 18 PM" src="https://github.com/gtkwave/gtkwave/assets/124410812/679279fb-d98c-428d-bff7-d9665464027b">
<img width="260" alt="Screenshot 2023-11-03 at 7 47 21 PM" src="https://github.com/gtkwave/gtkwave/assets/124410812/32c17797-5b68-469c-bedf-9cf2eb1be3af">

This are popup when we open gtkwaves kindly resolve this issue

**Comment by rfuest** [comment]
Try to use the homebrew version from this issue: https://github.com/gtkwave/gtkwave/issues/250

**Comment by rfuest** [comment]
I'm closing this issue, any issues with running with current macOS version should be discussed in #250.
