### ISSUE TITLE
Closing SST panel does not increase waves room

### ISSUE THREAD

**Issue by jotego** [gtkwave/gtkwave#33]
When I click on the SST arrow (at the top of the design hierarchy) the left panel goes blank but its window area is still shown. I would have expected to see the signals and waves windows move left and take more room. That is the behaviour in SimVision, for instance. So clicking on SST toggles between showing the design or giving more room to waveforms.

My version is 3.3.103, just in case this has already been addressed.

Thank you

**Comment by gtkwave** [comment]
It's a toolkit limitation where the blank SST doesn't collapse. You still should be able to drag the pane over to the left and reclaim most of the room.

-Tony
     On Saturday, November 14, 2020, 01:11:49 AM EST, Jose Tejada <notifications@github.com> wrote:  
 
 


When I click on the SST arrow (at the top of the design hierarchy) the left panel goes blank but its window area is still shown. I would have expected to see the signals and waves windows move left and take more room. That is the behaviour in SimVision, for instance. So clicking on SST toggles between showing the design or giving more room to waveforms.

My version is 3.3.103, just in case this has already been addressed.

Thank you

**Comment by jotego** [comment]
I understand. I can drag it manually, yes. Thank you.
