### ISSUE TITLE
Edge counter

### ISSUE THREAD

**Issue by jotego** [gtkwave/gtkwave#34]
A simple tool I often miss in GTKWave is the edge counter. You can find it in SimVision. It just counts the number of edges (posedge and neged) in between the cursors for the selected waveforms. You often want to count them to verify relationships between signals.

I would like to kindly request this new feature.

**Comment by gtkwave** [comment]
Highlight your signal(s).
Search->Pattern Search 1
adjust buttons as appropriate

-Tony

     On Saturday, November 14, 2020, 01:13:52 AM EST, Jose Tejada <notifications@github.com> wrote:  
 
 


A simple tool I often miss in GTKWave is the edge counter. You can find it in SimVision. It just counts the number of edges (posedge and neged) in between the cursors for the selected waveforms. You often want to count them to verify relationships between signals.

I would like to kindly request this new feature.

**Comment by jotego** [comment]
That sure works for me! Thank you
