### ISSUE TITLE
Abnormal memory usage in rtlbrowse

### ISSUE THREAD

**Issue by FurryAcetylCoA** [gtkwave/gtkwave#361]
When using rtlbrowse to browse smaller designs, such as `example/des.v`, and navigate though the tree selector. The virtual memory usage spikes to over 1000G before returning to a normal level. 
For larger designs, this spike can exceed 100T and the rtlbrowse just freeze.

It appears this isn't a classic memory leak. Given that in the first scenario where memory usage does return to a normal level after a few seconds.

Also, this issue doesn't seem to exist in gtkwave 3.3 lts 

I'm looking into this further and will post updates here. 

By the way, have there been any changes or updates in GTKWave that might affect its interaction with rtlbrowse?

**Comment by rfuest** [comment]
TBH I haven't looked at RTLBrowse in a very long time, it is very likely that I've broken something during the refactoring. The communication between RTLBrowse and GTKWave does use some kind of custom IPC implementation that uses shared memory and I would guess that the abnormal memory consumption could have something to do with that. In the long term it would be more better to replace this with D-Bus.

Let me know if I should take a closer look at this.

**Comment by tbybell** [comment]
There should be no IPC if rtlbrowse is run standalone.  That would make this much easier to debug as rtlbrowse would be its own process.

Does the high memory usage occur during initialization or manipulation of the tree with opening and closing nodes, viewing source files, etc?  (i.e., is it a GTK callback issue?)

I'd say just use strace(), a debugging malloc library, etc. to look for abnormally large malloc/calloc/realloc/etc.  If could be anything from an uninitialized or corrupted variable causing abnormally large allocations (freed with corresponding frees) all the way to recursion gone crazy somewhere such as callbacks triggering callbacks triggering callbacks...

**Comment by rfuest** [comment]
I just tried to run `rtlbrowse` built from the latest GIT revision and it seemed to work without any abnormal memory consumption.

One thing that caused issues for me at first was that the development version of GTKWave did start `rtlbrowse` from the distribution package instead of one in the build directory. The memory layout seems to have changed and the two versions aren't compatible with each other, which can cause all sorts of strange problems. If you run `meson devenv` before running `gtkwave` meson will setup the path to run the development version of `rtlbrowse` instead.

**Comment by FurryAcetylCoA** [comment]
> I'd say just use strace(), a debugging malloc library, etc. to look for abnormally large malloc/calloc/realloc/etc. 

> If you run meson devenv before running gtkwave meson will setup the path to run the development version of rtlbrowse instead.

Thanks for the advice! 
Valgrind reveals the source of memory spikes. It comes from `bwlogbox_2` within `logfile.c`
This issue arises when viewing source files, particularly upon clicking a node.
![Valgrind screenshot](https://github.com/gtkwave/gtkwave/assets/68182718/91681a8b-a3bd-46e9-b1da-12093897d487)

> I just tried to run rtlbrowse built from the latest GIT revision and it seemed to work without any abnormal memory consumption.

For my environment a stable way to recreate & log this issues is:
1. `meson devenv -C build` `cd ../examples`.
2.  `valgrind --tool=massif --trace-children=yes  --stacks=yes gtkwave des.fst --stems des.stems` .
3.  click the ">" at `TOP` node. 
4.  click the `top` node itself. 
5.  use any tools you like to read the report (`ms_print` or `massif-visualizer`).

To make this more obvious, you can add a null check after the `malloc` in `bwlogbox_2:1738`

I am currently analyzing the call graph to trace the origin of these spikes more accurately.

**Comment by FurryAcetylCoA** [comment]
I found it.
In `logfile.c:28`
```c
extern size_t yyleng;
```
however. In `vlex.c`
```c
int yyleng;
```

On 64-bit system sizeof(size_t) != sizeof(int) 

According to [The Single UNIX ® Specification, Version 2](https://pubs.opengroup.org/onlinepubs/7908799/xcu/lex.html)

> The external **int** yyleng is set to the length of the matching string. 

Thanks again for everyone's help. I am preparing a PR for this.
