### ISSUE TITLE
Cannot load dumpfile in new window

### ISSUE THREAD

**Issue by yikkrubz** [gtkwave/gtkwave#378]
When I try to load a dumpfile via File -> Open New Window, gtkwave prints in the terminal: Unable to find application named 'gtkwave' (see below). Loading the dumpfile via File -> Open New Tab or as a command line argument works as expected.

gtkwave git version updated today
macos 14.6.1 (intel)
MacPorts base version 2.10.0

$ which gtkwave
/usr/local/bin/gtkwave

$ gtkwave
(gtkwave:85994): GLib-GObject-CRITICAL **: 19:53:42.397: g_object_set_is_valid_property: object class 'GwColorTheme' has no property named 'marker-baseline'

(gtkwave:85994): GLib-GObject-CRITICAL **: 19:53:42.397: g_object_set_is_valid_property: object class 'GwColorTheme' has no property named 'waveform-value'

(gtkwave:85994): GLib-GObject-CRITICAL **: 19:53:42.397: g_object_set_is_valid_property: object class 'GwColorTheme' has no property named 'vector-stroke'

(gtkwave:85994): GLib-GObject-CRITICAL **: 19:53:42.397: g_object_set_is_valid_property: object class 'GwColorTheme' has no property named 'marker-unnamed'

(gtkwave:85994): GLib-GObject-CRITICAL **: 19:53:42.397: g_object_set_is_valid_property: object class 'GwColorTheme' has no property named 'marker-named'

GTKWave Analyzer v3.4.0 (w)1999-2022 BSI

GTKWAVE | Use the -h, --help command line flags to display help.
Unable to find application named 'gtkwave'

```
git diff
diff --git a/lib/libgtkwave/src/gw-fst-file.c b/lib/libgtkwave/src/gw-fst-file.c
diff --git a/lib/libgtkwave/src/gw-fst-file.c b/lib/libgtkwave/src/gw-fst-file.c
index 9256fa4..c5e359c 100644
--- a/lib/libgtkwave/src/gw-fst-file.c
+++ b/lib/libgtkwave/src/gw-fst-file.c
@@ -262,7 +262,7 @@ static void fst_callback2(void *user_callback_data_pointer,
 }
 
 static void fst_callback(void *user_callback_data_pointer,
-                         guint64 tim,
+                         uint64_t tim,
                          fstHandle txidx,
                          const unsigned char *value)
 {
diff --git a/meson.build b/meson.build
index d1edbe4..8e41f25 100644
--- a/meson.build
+++ b/meson.build
@@ -228,6 +228,5 @@ subdir('contrib')
 
 gnome.post_install(
     update_mime_database: get_option('update_mime_database'),
-    update_desktop_database: true,
     gtk_update_icon_cache: true,

```

**Comment by rfuest** [comment]
Try to change this line: https://github.com/gtkwave/gtkwave/blob/d2005675801b89ef0201c6968cee8419847dc5af/src/menu.c#L2337
into
```c
#if 1
```
to see if this fixes the issue.

**Comment by yikkrubz** [comment]
Thank you very much for your reply.

While running meson setup build, meson detects gtk-mac-integration-gtk3, gtk3 and gtk4.
The gtkwave binary is linked with libgtk3 and libgtkmacintegration-gtk3.4 (see below).

When I change the #ifdef MAC_INTEGRATION to a #if 0 in line 2337 of src/menu.c, the issue is resolved.

gtkwave git version updated today
macos 14.6.1 (intel)
MacPorts base version 2.10.0

$ which gtkwave
/usr/local/bin/gtkwave

$ meson setup build
The Meson build system
Version: 1.5.1
Source dir: /Users/Peter/Downloads/tmp/gtkwave
Build dir: /Users/Peter/Downloads/tmp/gtkwave/build
Build type: native build
Project name: gtkwave
Project version: 3.4.0
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C linker for the host machine: cc ld64 1053.12
C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C++ linker for the host machine: c++ ld64 1053.12
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/opt/local/bin/pkg-config) 0.29.2
Run-time dependency glib-2.0 found: YES 2.78.4
Run-time dependency gobject-2.0 found: YES 2.78.4
Run-time dependency gtk+-3.0 found: YES 3.24.42
Run-time dependency gtk4 found: YES 4.14.3
Run-time dependency gtk+-unix-print-3.0 found: YES 3.24.42
Run-time dependency gtk-mac-integration-gtk3 found: YES 3.0.1
Run-time dependency zlib found: YES 1.3.1
Library m found: YES
Has header "Judy.h" : NO 
Has header "regex.h" : YES 
Library regex found: NO
Run-time dependency threads found: YES
Found CMake: /opt/local/bin/cmake (3.29.5)
Run-time dependency bzip2 found: YES 1.0.8
Program gperf found: YES (/usr/bin/gperf)
Program flex found: YES (/opt/local/bin/flex)
Has header "inttypes.h" : YES 
Has header "sys/stat.h" : YES 
Has header "alloca.h" : YES 
Has header "getopt.h" : YES 
Has header "fcntl.h" : YES 
Has header "unistd.h" : YES 
Checking for function "fseeko" : YES 
Checking for function "realpath" : YES 
Checking for function "setenv" : YES 
Checking for function "unsetenv" : YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Werror=address: YES 
Compiler for C supports arguments -Werror=array-bounds: YES 
Compiler for C supports arguments -Werror=empty-body: YES 
Compiler for C supports arguments -Werror=implicit: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=int-conversion: YES 
Compiler for C supports arguments -Werror=int-to-pointer-cast: YES 
Compiler for C supports arguments -Werror=main: YES 
Compiler for C supports arguments -Werror=misleading-indentation: YES 
Compiler for C supports arguments -Werror=missing-braces: YES 
Compiler for C supports arguments -Werror=missing-include-dirs: YES 
Compiler for C supports arguments -Werror=nonnull: YES 
Compiler for C supports arguments -Werror=overflow: YES 
Compiler for C supports arguments -Werror=parenthesis: NO 
Compiler for C supports arguments -Werror=pointer-arith: YES 
Compiler for C supports arguments -Werror=pointer-to-int-cast: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=sequence-point: YES 
Compiler for C supports arguments -Werror=shadow: YES 
Compiler for C supports arguments -Werror=strict-prototypes: YES 
Compiler for C supports arguments -Werror=trigraphs: YES 
Compiler for C supports arguments -Werror=undef: YES 
Compiler for C supports arguments -Werror=write-strings: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Wlogical-op: NO 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wunused: YES 
Configuring config.h using configuration
Dependency glib-2.0 found: YES 2.78.4 (cached)
Program /opt/local/bin/glib-mkenums found: YES (/opt/local/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.4 (cached)
Program /opt/local/bin/glib-mkenums found: YES (/opt/local/bin/glib-mkenums)
Run-time dependency gobject-introspection-1.0 found: YES 1.78.1
Dependency gobject-introspection-1.0 found: YES 1.78.1 (cached)
Program /opt/local/bin/g-ir-scanner found: YES (/opt/local/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.78.1 (cached)
Program /opt/local/bin/g-ir-compiler found: YES (/opt/local/bin/g-ir-compiler)
Program diff found: YES (/usr/bin/diff)
Build-time dependency gio-2.0 found: YES 2.78.4
Program /opt/local/bin/glib-compile-resources found: YES (/opt/local/bin/glib-compile-resources)
Program gtk4-update-icon-cache found: YES (/opt/local/bin/gtk4-update-icon-cache)
Program update-mime-database found: YES (/opt/local/bin/update-mime-database)
Build targets in project: 73

Found ninja-1.12.1 at /opt/local/bin/ninja

$ otool -L gtkwave
gtkwave:
	/usr/local/lib/libgtkwave.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/opt/local/lib/libglib-2.0.0.dylib (compatibility version 7801.0.0, current version 7801.4.0)
	/opt/local/lib/libgtk-3.0.dylib (compatibility version 2411.0.0, current version 2411.32.0)
	/opt/local/lib/libgdk-3.0.dylib (compatibility version 2411.0.0, current version 2411.32.0)
	/opt/local/lib/libpangocairo-1.0.0.dylib (compatibility version 5201.0.0, current version 5201.2.0)
	/opt/local/lib/libpango-1.0.0.dylib (compatibility version 5201.0.0, current version 5201.2.0)
	/opt/local/lib/libcairo.2.dylib (compatibility version 11709.0.0, current version 11709.0.0)
	/opt/local/lib/libgdk_pixbuf-2.0.0.dylib (compatibility version 4201.0.0, current version 4201.12.0)
	/opt/local/lib/libgio-2.0.0.dylib (compatibility version 7801.0.0, current version 7801.4.0)
	/opt/local/lib/libgobject-2.0.0.dylib (compatibility version 7801.0.0, current version 7801.4.0)
	/opt/local/lib/gtkmacintegration-gtk3/libgtkmacintegration-gtk3.4.dylib (compatibility version 5.0.0, current version 5.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2487.50.124)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 2420.0.0)

```
$ git diff
diff --git a/lib/libgtkwave/src/gw-fst-file.c b/lib/libgtkwave/src/gw-fst-file.c
index 9256fa4..c5e359c 100644
--- a/lib/libgtkwave/src/gw-fst-file.c
+++ b/lib/libgtkwave/src/gw-fst-file.c
@@ -262,7 +262,7 @@ static void fst_callback2(void *user_callback_data_pointer,
 }
 
 static void fst_callback(void *user_callback_data_pointer,
-                         guint64 tim,
+                         uint64_t tim,
                          fstHandle txidx,
                          const unsigned char *value)
 {
diff --git a/meson.build b/meson.build
index d1edbe4..8e41f25 100644
--- a/meson.build
+++ b/meson.build
@@ -228,6 +228,5 @@ subdir('contrib')
 
 gnome.post_install(
     update_mime_database: get_option('update_mime_database'),
-    update_desktop_database: true,
     gtk_update_icon_cache: true,
 )
diff --git a/src/menu.c b/src/menu.c
index 5a476e2..18ae716 100644
--- a/src/menu.c
+++ b/src/menu.c
@@ -2334,7 +2334,7 @@ void menu_new_viewer_cleanup(GtkWidget *widget, gpointer data)
             return;
         }
 
-#ifdef MAC_INTEGRATION
+#if 0
         /* from : @pfx = split(' ', "open -n -W -a gtkwave --args --chdir dummy"); */
         if (GLOBALS->optimize_vcd) {
             execlp("open",
```

**Comment by rfuest** [comment]
A related issue just came up in #250. The code that is used when `MAC_INTEGRATION` is defined seems to only work when GTKWave is installed as a macOS `.app`. I'll temporarily disable this code in the development version, because Homebrew is the only semi supported way of installing the development version of GTKWave on macOS at the moment.

**Comment by rfuest** [comment]
I've committed fixes for the type issue and the open in new window feature the the repo. (#379)

**Comment by yikkrubz** [comment]
Thank you very much for committing the fixes.
