### ISSUE TITLE
Icons for the menu bar are not showing up in Ubuntu.

### ISSUE THREAD

**Issue by wel97459** [gtkwave/gtkwave#38]
The icons on the menu bar are not showing up after loading a waveform file.
  
When I first launch GTKWave the disabled icons are shown:
![image](https://user-images.githubusercontent.com/12990640/101205770-fb6dd800-3622-11eb-8c6d-33572471006a.png)
 
But after loading a file the icons are no longer shown:
![image](https://user-images.githubusercontent.com/12990640/101206127-877fff80-3623-11eb-8b1a-e6f732e4d3a7.png)

I first installed GTKWave with apt-get, and just pulled down this repo and compiled it, with no luck.

**Comment by gtkwave** [comment]
Those are stock icons so I don't know what is going on with that.
Do you see missing stock icons in gtk-demo or gtk3-demo (whichever version gtkwave is using)?

If you don't know what version gtkwave is using either run the ldd command against the gtkwave binary (wherever it is located) to see what libraries are used or simply check both of the gtk demos.

-Tony


     On Friday, December 4, 2020, 02:26:04 PM EST, Winston Lowe <notifications@github.com> wrote:  
 
 


The icons on the menu bar are not showing up after loading a waveform file.

When I first launch GTKWave the disabled icons are shown:


But after loading a file the icons are no longer shown:


I first installed GTKWave with apt-get, and just pulled down this repo and compiled it, with no luck.

**Comment by wel97459** [comment]
Seems that gtkwave was picking up on the dark theme setting and making the icons lighter and not drak, and since the color of the window stays white/gray I couldn't see them.

**Comment by gtkwave** [comment]
At least for the gtk3 version you should be able to try this command line flag:

 -6, --dark set gtk-application-prefer-dark-theme = TRUE

...for some reason it doesn't always communicate back to the application. I don't know why.

-Tony


     On Friday, December 4, 2020, 02:26:04 PM EST, Winston Lowe <notifications@github.com> wrote:  
 
 


The icons on the menu bar are not showing up after loading a waveform file.

When I first launch GTKWave the disabled icons are shown:


But after loading a file the icons are no longer shown:


I first installed GTKWave with apt-get, and just pulled down this repo and compiled it, with no luck.

**Comment by wel97459** [comment]
Thanks for your help I'll give it a try.
