### ISSUE TITLE
Signals windows background is not colored by most (all?) popular dark themes

### ISSUE THREAD

**Issue by anhangaba** [gtkwave/gtkwave#4]
![Image](https://i.imgur.com/kPO9gGv.png)

I tried a few dark themes and none colored the signal window background. I'm not sure if this is an issue from the themes or gtkwave.

I tired on
GTKWave Analyzer v3.3.100 (w)1999-2019 BSI

**Comment by gtkwave** [comment]
First, if you're not already doing it, use the gtk3 version of gtkwave.

If this autodetect code fails:
#if GTK_CHECK_VERSION(3,0,0)
 if(GLOBALS->use_dark)
 {
 g_object_set(gtk_settings_get_default(), "gtk-application-prefer-dark-theme", TRUE, NULL);
 }
#endif

also add --dark to your command line.

-Tony


     On Saturday, February 22, 2020, 06:24:12 PM EST, anhangaba <notifications@github.com> wrote:  
 
 


I tried a few dark themes and none colored the signal window background. I'm not sure if this is an issue from the themes or gtkwave.

I tired on
GTKWave Analyzer v3.3.100 (w)1999-2019 BSI

**Comment by anhangaba** [comment]
It worked with `--dark`. Thanks.
