### ISSUE TITLE
Keyboard shortcuts do not work in TwinWave

### ISSUE THREAD

**Issue by ripopov** [gtkwave/gtkwave#47]
I invoke it like this:
$ twinwave bad.fst + good.fst

Keyboard shortcuts do not work. Have to use mouse to add and remove signals.

**Comment by gtkwave** [comment]
This is a limitation of gtkplug and socket inside a paned window.

Open twinwave with two windows and it should work.

-Tony


twinwave arglist1 separator arglist2

The '+' between argument lists splits and creates one window.
The '++' between argument lists splits and creates two windows.


     On Saturday, March 13, 2021, 04:18:00 PM EST, Roman Popov ***@***.***> wrote:  
 
 


I invoke it like this:
$ twinwave bad.fst + good.fst

Keyboard shortcuts do not work. Have to use mouse to add and remove signals.

**Comment by ripopov** [comment]
Indeed, two windows work. Thank you!
