### ISSUE TITLE
How do I measure the difference between 2 markers?

### ISSUE THREAD

**Issue by HaFred** [gtkwave/gtkwave#6]
Cannot believe that there is no such function... Or could somebody please tell me how to do it? Greatly appreciate it.

**Comment by gtkwave** [comment]
Center mouse button to add/remove white baseline marker.
Left mouse button to place the red "normal" marker.

You will see a B+/- distance for the marker time, "B" being relative to the baseline marker.

-Tony
     On Thursday, March 12, 2020, 01:33:13 AM EDT, Frederick HONG <notifications@github.com> wrote:  
 
 


Cannot believe that there is no such function... Or could somebody please tell me how to do it? Greatly appreciate it.
