### ISSUE TITLE
GUI broken on Fedora 34

### ISSUE THREAD

**Issue by zero9178** [gtkwave/gtkwave#62]
Opening GTKWave installed from Fedoras repositories currently yields following window for me:
![Screenshot from 2021-05-10 14-28-10](https://user-images.githubusercontent.com/6625526/117659634-7cb23380-b19c-11eb-840c-ba05611ac7c5.png)

Loading a vcd file and such works but does not change the GUI much. 

Extra info:
Fedora 34 uses GNOME 40.1 and Wayland. My Laptop has a touchscreen which GTKWave seems to detect according to logging messages in the terminal.

**Comment by gtkwave** [comment]
Is it the gtk2 or gtk3 version. If you ldd on the binary, what gtk libraries (and gtk versions) are used?

A blank screen sounds like they fundamentally broke something in GTK/Gnome/Wayland--especially if for example it appears fine through a locally run VNC session.

Thanks,
-Tony

     On Monday, May 10, 2021, 08:32:41 AM EDT, zero9178 ***@***.***> wrote:  
 
 


Opening GTKWave installed from Fedoras repositories currently yields following window for me:


Loading a vcd file and such works but does not change the GUI much.

Extra info:
Fedora 34 uses GNOME 40.1 and Wayland. My Laptop has a touchscreen which GTKWave seems to detect according to logging messages in the terminal.

**Comment by gtkwave** [comment]
Last night, I upgraded my touch laptop to F34 and gtkwave worked fine for me in both x11 and Wayland. I don't know what is going on with your system. If this isn't specific to your system, I don't know what it would be.

-Tony


     On Monday, May 10, 2021, 10:04:30 AM EDT, zero9178 ***@***.***> wrote:  
 
 


Running:
***@***.*** ~]$ which ***@***.*** ~]$ cd ***@***.*** bin]$ ldd gtkwave	linux-vdso.so.1 (0x00007ffff716e000)	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007fc7397a6000)	libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007fc7396a1000)	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007fc73968f000)	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007fc73963d000)	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007fc739521000)	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007fc7394f1000)	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007fc73931b000)	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fc7392c0000)	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fc739186000)	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fc73915a000)	libz.so.1 => /lib64/libz.so.1 (0x00007fc739140000)	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc73912d000)	libtcl8.6.so => /lib64/libtcl8.6.so (0x00007fc738f7d000)	libtk8.6.so => /lib64/libtk8.6.so (0x00007fc738e15000)	libJudy.so.1 => /lib64/libJudy.so.1 (0x00007fc738dc4000)	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc738da3000)	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc738d9c000)	libm.so.6 => /lib64/libm.so.6 (0x00007fc738c58000)	libc.so.6 => /lib64/libc.so.6 (0x00007fc738a87000)	libcloudproviders.so.0 => /lib64/libcloudproviders.so.0 (0x00007fc738a6d000)	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007fc738a67000)	libX11.so.6 => /lib64/libX11.so.6 (0x00007fc738920000)	libXi.so.6 => /lib64/libXi.so.6 (0x00007fc73890e000)	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007fc738905000)	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007fc7388f7000)	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007fc7388ce000)	libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007fc738895000)	libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007fc738884000)	libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007fc73874f000)	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007fc738731000)	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007fc738714000)	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007fc738644000)	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fc7385f6000)	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fc738532000)	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007fc73852d000)	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007fc738520000)	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007fc738511000)	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007fc73850c000)	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007fc738507000)	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007fc7384be000)	libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007fc7384b4000)	libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007fc7384af000)	libXext.so.6 => /lib64/libXext.so.6 (0x00007fc738498000)	librt.so.1 => /lib64/librt.so.1 (0x00007fc73848d000)	libthai.so.0 => /lib64/libthai.so.0 (0x00007fc738482000)	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007fc7383d6000)	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fc73839d000)	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007fc738396000)	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fc73836b000)	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007fc73835b000)	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007fc73834e000)	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007fc7382d5000)	libmount.so.1 => /lib64/libmount.so.1 (0x00007fc738292000)	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fc738264000)	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc73824a000)	libffi.so.6 => /lib64/libffi.so.6 (0x00007fc73823f000)	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fc7381c7000)	libXft.so.2 => /lib64/libXft.so.2 (0x00007fc7381ae000)	/lib64/ld-linux-x86-64.so.2 (0x00007fc73a10a000)	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc738191000)	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007fc73813f000)	libatspi.so.0 => /lib64/libatspi.so.0 (0x00007fc738102000)	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fc7380e1000)	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007fc737f58000)	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007fc737f48000)	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007fc737f3f000)	libXau.so.6 => /lib64/libXau.so.6 (0x00007fc737f39000)	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fc737f04000)	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fc737e6d000)	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007fc737da6000)	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007fc737d83000)	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007fc737cbe000)	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007fc737c9a000)	libcap.so.2 => /lib64/libcap.so.2 (0x00007fc737c90000)	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007fc737b53000)	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007fc737b2d000)
Seems like it is linked against gtk-3

**Comment by zero9178** [comment]
Fair enough. I will close this issue for now and try to investigate.

**Comment by paller** [comment]
I have the exact same problem and UI is the same on x11 and Wayland. If you find a way of fixing it, please share the details.

**Comment by gtkwave** [comment]
If this what can be installed via a package manager on Fedora or are you building from source?

I upgraded to F34 but I didn't update directly after that. I'll have to try that.

-Tony


     On Wednesday, May 12, 2021, 03:31:59 PM EDT, Palle Ravn ***@***.***> wrote:  
 
 


I have the exact same problem and UI is the same on x11 and Wayland. If you find a way of fixing it, please share the details.

**Comment by paller** [comment]
It's the one from the Fedora repository.

```
$ dnf info gtkwave
Installed Packages
Name         : gtkwave
Version      : 3.3.108
Release      : 2.fc34
Architecture : x86_64
Size         : 4.2 M
Source       : gtkwave-3.3.108-2.fc34.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Waveform Viewer
URL          : http://gtkwave.sourceforge.net/
License      : GPLv2+
```

I will try building from source to see if that's any better.

**Comment by paller** [comment]
Building locally with `--enable-gtk3` works fine. It might just be a configuration error by the package maintainer.

**Comment by gtkwave** [comment]
OK, then please send a note to Paul Howarth, or report it however it's usually done. He's been really on top of things as a maintainer over the years.

https://fedoraproject.org/wiki/User:Pghmcfc

Thanks,
-Tony


     On Thursday, May 13, 2021, 08:22:20 AM EDT, Palle Ravn ***@***.***> wrote:  
 
 


Building locally with --enable-gtk3 works fine. It might just be a configuration error by the package maintainer.

**Comment by paller** [comment]
Already reported under https://bugzilla.redhat.com/show_bug.cgi?id=1956191

**Comment by pghmcfc** [comment]
Curious. I'm getting a similar issue with 3.3.108 on Fedora 33, built using the same RPM packaging as the Fedora version. The configure options used (for gtk3 version) are: `--disable-dependency-tracking --disable-mime-update --enable-gtk3 --enable-judy --with-gsettings --with-tirpc`. For the people that got a working build locally, did you just use `--enable-gtk3`?

**Comment by paller** [comment]
> Curious. I'm getting a similar issue with 3.3.108 on Fedora 33, built using the same RPM packaging as the Fedora version. The configure options used (for gtk3 version) are: `--disable-dependency-tracking --disable-mime-update --enable-gtk3 --enable-judy --with-gsettings --with-tirpc`. For the people that got a working build locally, did you just use `--enable-gtk3`?

Correct. Only applied `--enable-gtk3`.

**Comment by gtkwave** [comment]
I'd ask for the heck of it if rendering to this is broken as well:
https://developer.gnome.org/gtk3/stable/gtk-broadway.html

I'm curious is there is some kind of video chipset issue in a driver or something and for some odd reason the way gtkwave drives GDK triggers it.

-Tony     On Sunday, May 16, 2021, 07:46:10 AM EDT, Palle Ravn ***@***.***> wrote:  
 
 



Curious. I'm getting a similar issue with 3.3.108 on Fedora 33, built using the same RPM packaging as the Fedora version. The configure options used (for gtk3 version) are: --disable-dependency-tracking --disable-mime-update --enable-gtk3 --enable-judy --with-gsettings --with-tirpc. For the people that got a working build locally, did you just use --enable-gtk3?


Correct. Only applied --enable-gtk3.

**Comment by paller** [comment]
> I'd ask for the heck of it if rendering to this is broken as well: https://developer.gnome.org/gtk3/stable/gtk-broadway.html I'm curious is there is some kind of video chipset issue in a driver or something and for some odd reason the way gtkwave drives GDK triggers it.
> […](#)

It is also broken. The glitches are more or less the same as the native rendering.

Regarding video chipset I'm running on Intel Integrated Graphics.

**Comment by gtkwave** [comment]
OK, thanks. That shows it's not video driver related. I had no problems on my F34 install.

What is the gtk version in gtkversion.h (probably found at /usr/include/gtk-3.0/gtk/).
GTK_MAJOR_VERSION
GTK_MINOR_VERSION
GTK_MICRO_VERSION

I might have to build GTK from that version of source to see what is potentially going on here. If I had any guesses, it somehow involves gdk_window_begin_frame() and gdk_window_end_draw_frame(). Nothing else makes a whole lot of sense here.

https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-end-draw-frame

Thanks,
-Tony
     On Sunday, May 16, 2021, 02:47:15 PM EDT, Palle Ravn ***@***.***> wrote:  
 
 



I'd ask for the heck of it if rendering to this is broken as well: https://developer.gnome.org/gtk3/stable/gtk-broadway.html I'm curious is there is some kind of video chipset issue in a driver or something and for some odd reason the way gtkwave drives GDK triggers it.
…


It is also broken. The glitches are more or less the same as the native rendering.

Regarding video chipset I'm running on Intel Integrated Graphics.

**Comment by paller** [comment]
> ... What is the gtk version in gtkversion.h (probably found at /usr/include/gtk-3.0/gtk/). GTK_MAJOR_VERSION GTK_MINOR_VERSION GTK_MICRO_VERSION

gtkversion.h:#define GTK_MAJOR_VERSION (3)
gtkversion.h:#define GTK_MINOR_VERSION (24)
gtkversion.h:#define GTK_MICRO_VERSION (29)

**Comment by gtkwave** [comment]
Paul,

I installed the gtkwave RPM on F34 and got the blank screen, and various toolbar buttons/widgets that wouldn't render unless the mouse was on top of them. I noticed the red, primary marker shows up on occasion so this seems to be something involving pixmaps, image buffer, or something similar.

Compiling against source with the flags you show below worked ok for me.

Thanks,
-Tony

     On Friday, May 14, 2021, 11:45:18 AM EDT, Paul Howarth ***@***.***> wrote:  
 
 


Curious. I'm getting a similar issue with 3.3.108 on Fedora 33, built using the same RPM packaging as the Fedora version. The configure options used (for gtk3 version) are: --disable-dependency-tracking --disable-mime-update --enable-gtk3 --enable-judy --with-gsettings --with-tirpc. For the people that got a working build locally, did you just use --enable-gtk3?

**Comment by pghmcfc** [comment]
I wonder if it's related to the build environment? The RPM packages are built in an environment where only the specifically-requested build dependencies (and their dependencies, recursively) are there. It's possible that your build environment has something in it that the RPM build doesn't have.

Today I tried building the 3.3.107 version in the Fedora 34 RPM build environment. That worked OK. Using exactly the same flow to rebuild 3.3.108 did not work. Something has changed between the two that is resulting in this issue but I haven't figured out what it might be yet.

**Comment by gtkwave** [comment]
Strangely, as far as I know, the only difference between the two is that there are minor bugfixes.

I diffed the ./configure files between 3.3.107 and 3.3.108 and noticed no appreciable difference as well.
I'm wondering if this is yet another compiler optimization problem where something is subtle enough in the memory footprint to break. I don't see anything blatant when I run valgrind on any of the executables, either. Can you try forcing the CFLAGS to -O0 only?

ldd shows no difference in library usage.

Thanks,
-Tony


     On Tuesday, May 18, 2021, 10:16:25 AM EDT, Paul Howarth ***@***.***> wrote:  
 
 


I wonder if it's related to the build environment? The RPM packages are built in an environment where only the specifically-requested build dependencies (and their dependencies, recursively) are there. It's possible that your build environment has something in it that the RPM build doesn't have.

Today I tried building the 3.3.107 version in the Fedora 34 RPM build environment. That worked OK. Using exactly the same flow to rebuild 3.3.108 did not work. Something has changed between the two that is resulting in this issue but I haven't figured out what it might be yet.

**Comment by pghmcfc** [comment]
I tried it with -O0 and that looks to fix it.

**Comment by gtkwave** [comment]
I'll integrate those obvious goofs...strangely enough when I compile on Centos7 I don't see any warnings. I suppose the stack frame was aligned just good enough to work.

When I compile in FC, there are so many deprecation warnings inside the gtk headers that I missed seeing any real warnings.

Good catch, thanks.
-Tony


     On Wednesday, May 19, 2021, 09:08:25 AM EDT, Paul Howarth ***@***.***> wrote:  
 
 


I tried fixing a couple of warnings that showed up in the build log. One of them (I rather suspect the first one) seems to have fixed it for me:
--- src/gtk23compat.c+++ src/gtk23compat.c@@ -171,6 +171,7 @@ gint XXX_gtk_widget_get_scale_factor (Gt { #if GTK_CHECK_VERSION(3,0,0) gint rc = widget ? gtk_widget_get_scale_factor(widget) : 1;+return rc; #else return(1); #endif--- src/wavewindow.c+++ src/wavewindow.c@@ -2387,7 +2387,7 @@ if(GLOBALS->swipe_init_time) 	{ 	GDateTime *gd2 = g_date_time_new_now_utc(); 	GTimeSpan elapsed = g_date_time_difference(gd2, GLOBALS->swipe_init_time);-	gdouble decaying;+	gdouble decaying = 0.0; 	g_date_time_unref(gd2); 	if(elapsed < WAVE_GTK3_SWIPE_MICROSECONDS) 		{
Could anyone try this scratch build for Fedora 34? If everyone's happy with it I'll do a proper update.
https://koji.fedoraproject.org/koji/taskinfo?taskID=68261762

**Comment by pghmcfc** [comment]
There is now an official update available in the updates-testing repository:
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2b4f053d12

Regarding warnings, gtkwave seems to generate a remarkably low number of them actually, so by searching the build log for "warning:" and skipping through the deprecation warnings (most of which look like the same thing to me), there wasn't actually much left. I looked at the ones that looked most likely to have a functional impact, which were the ones about reaching the end of a non-void function and possible use of uninitialized data, and got lucky with my first attempt at fixing some of them :-)

**Comment by gtkwave** [comment]
Paul,

Thanks for looking into and fixing this. I put those changes in revision control so they'll be in the next release.

-Tony


     On Friday, May 21, 2021, 06:32:55 AM EDT, Paul Howarth ***@***.***> wrote:  
 
 


There is now an official update available in the updates-testing repository:
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2b4f053d12

Regarding warnings, gtkwave seems to generate a remarkably low number of them actually, so by searching the build log for "warning:" and skipping through the deprecation warnings (most of which look like the same thing to me), there wasn't actually much left. I looked at the ones that looked most likely to have a functional impact, which were the ones about reaching the end of a non-void function and possible use of uninitialized data, and got lucky with my first attempt at fixing some of them :-)

**Comment by zero9178** [comment]
Just received the update on stable Fedora 34, and can happily confirm that it is indeed fixed.
